# Case Study on Testing of Hypothesis
**Sreehari P S**<br>
*NORKA B5*
***

### Statement
A company started to invest in digital marketing as a new way of their product promotions.For that they collected data and decided to carry out a study on it.<br>
● The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.<br>
● The company needs to check whether there is any dependency between the features “Region” and “Manager”.<br>
Help the company to carry out their study with the help of data provided.<br>
***

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./datasets/Sales_add.csv')
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [3]:
data.describe().transpose().round(2)

count       mean       std       min  \
Sales_before_digital_add(in $)   22.0  149239.95  14844.04  130263.0   
Sales_After_digital_add(in $)    22.0  231123.73  25556.78  187305.0   

                                      25%       50%       75%       max  
Sales_before_digital_add(in $)  138087.75  147444.0  157627.5  178939.0  
Sales_After_digital_add(in $)   214960.75  229986.5  250909.0  276279.0

In [4]:
data.shape

(22, 5)

### 1: The company wishes to clarify whether there is any increase in sales after stepping into digital marketing

**Hypthesis**<br>
H0 = Sales didnot increase after digital marketing<br>
H1 = Sales increase after digital marketing

Hypothesis testing can be done with t-test as sample size is only 22
***

In [5]:
sales_before = data['Sales_before_digital_add(in $)']
sales_after = data['Sales_After_digital_add(in $)']

In [6]:
from scipy import stats

In [7]:
alpha = 0.05
t_dof = 21

In [8]:
t_critical = stats.t.ppf(q=1-alpha, df = t_dof)
print(f"Critical value = {t_critical}")
tvalue, p_value = stats.ttest_ind(sales_before,sales_after)
tvalue = np.abs(tvalue)
print(f"P value = {p_value}")
print(f"T value = {tvalue}")

Critical value = 1.7207429028118775
P value = 2.614368006904645e-16
T value = 12.995084451110877


In [9]:
if tvalue>=t_critical and p_value<=alpha:
    print("Reject H0")
else:
    print("Accept H0")

Reject H0


So from the test we can clearly conclude that sales did increase after digital marketing
***

### 2. The company needs to check whether there is any dependency between the features “Region” and "Manager”.

H0 = There is no dependency between Region and Manager
H1 = There is a dependency between Region and Manager

In [10]:
cont_table = pd.crosstab(data["Region"], data["Manager"])
print('Contingency_table :-\n',cont_table)
#Observed Values
Observed_Values = cont_table.values 
print("Observed Values :-\n",Observed_Values)

Contingency_table :-
 Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1
Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [11]:
tup=stats.chi2_contingency(cont_table)
Expected_Values = tup[3]
print("Expected Values :-\n",Expected_Values)

Expected Values :-
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]


In [12]:
dof=tup[2]
print("Degree of Freedom:-",dof)

Degree of Freedom:- 4


In [13]:
chis2=np.abs(tup[0])
print("Test Statistic:-",chis2)

Test Statistic:- 3.050566893424036


In [14]:
pvalue = tup[1]
print("PValue:-",pvalue)

PValue:- 0.5493991051158094


In [15]:
critical_value=stats.chi2.ppf(q=1-alpha,df=dof)
print(critical_value)

9.487729036781154


In [16]:
if chis2>=critical_value and pvalue<=alpha:
    print("Reject H0")
else:
    print("Accept H0")

Accept H0


Therefore it is clear that there is no dependency between Manager and Regions