# NumPy Basics

In [1]:
# Traditional summing of list
list1 = list(range(10))
list2 = list(range(11,21))
print(list1 + list2)
list3 = []
for i, j in zip(list1, list2):
    list3.append(i+j)
print(list3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]


<h1> Numpy functions

<h2>1. np.array

In [3]:
# Summing of list Using numpy
import numpy as np
arr1 = np.array(list1) #dtype = ndarray
arr2 = np.array(list2)
sum = arr1+arr2
print(sum)

[11 13 15 17 19 21 23 25 27 29]


In [4]:
# multdimensional array
# np.array converts given type into desired output
list4 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr_2d = np.array(list4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h2>Properties of ndarray

In [57]:
# data type of array
print(arr_2d.dtype)
# dimension of array
print(arr_2d.ndim)
# shape of array
print(arr_2d.shape)
#size
print(arr_2d.size)

int32
2
(3, 4)
12


<h3> More on np.array

In [82]:
# changing data types
arr3 = np.array(arr_2d,dtype=float)
print(f'arr3 :\n{arr3}\n')
print(f'arr3 type : {arr3.dtype}\n')
# all hetrogeneous collections are of type = object in np
arr4 = np.array([{'s':'d'},'1','np'])
print(f'arr4 :\n{arr4}')
print(f'arr4 type : {arr4.dtype}\n')
arr5 = np.array(arr4,dtype=list)
print(f'arr5 :\n{arr5}')
print(f'arr5 type : {arr5.dtype}')

arr3 :
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

arr3 type : float64

arr4 :
[{'s': 'd'} '1' 'np']
arr4 type : object

arr5 :
[{'s': 'd'} '1' 'np']
arr5 type : object


<h3>ndarray functions

In [66]:
#reshaape
arr6 = arr3.reshape(4,3)
print(f'arr6 :\n{arr6}')
#in reshape size of arrays should match

arr6 :
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


<h2> 2. np.arange

In [93]:
# similar to range function in python
arr7 = np.arange(1,20,3)
print(f'arr7 :\n{arr7}')

arr7 :
[ 1  4  7 10 13 16 19]


<h2> 3. np.linspace

In [94]:
#linspace function
#creates linearly distributed array, dividing array in n fractions
# n is _linspace_dispatcher()
arr8 = np.linspace(1,20,3)
print(f'arr8 :\n{arr8}')
print(f'arr8 type : {arr8.dtype}\n')
#cool
arr9 = np.linspace(arr8,10)
print(f'arr9 :\n{arr9}\n')
print(f'arr9 type : {arr9.dtype}\n')
print(f'arr9 shape : {arr9.shape}\n')
print(f'arr9 size : {arr9.size}\n')
print(f'arr9 dim : {arr9.ndim}\n')

arr8 :
[ 1.  10.5 20. ]
arr8 type : float64

arr9 :
[[ 1.         10.5        20.        ]
 [ 1.18367347 10.48979592 19.79591837]
 [ 1.36734694 10.47959184 19.59183673]
 [ 1.55102041 10.46938776 19.3877551 ]
 [ 1.73469388 10.45918367 19.18367347]
 [ 1.91836735 10.44897959 18.97959184]
 [ 2.10204082 10.43877551 18.7755102 ]
 [ 2.28571429 10.42857143 18.57142857]
 [ 2.46938776 10.41836735 18.36734694]
 [ 2.65306122 10.40816327 18.16326531]
 [ 2.83673469 10.39795918 17.95918367]
 [ 3.02040816 10.3877551  17.75510204]
 [ 3.20408163 10.37755102 17.55102041]
 [ 3.3877551  10.36734694 17.34693878]
 [ 3.57142857 10.35714286 17.14285714]
 [ 3.75510204 10.34693878 16.93877551]
 [ 3.93877551 10.33673469 16.73469388]
 [ 4.12244898 10.32653061 16.53061224]
 [ 4.30612245 10.31632653 16.32653061]
 [ 4.48979592 10.30612245 16.12244898]
 [ 4.67346939 10.29591837 15.91836735]
 [ 4.85714286 10.28571429 15.71428571]
 [ 5.04081633 10.2755102  15.51020408]
 [ 5.2244898  10.26530612 15.30612245]
 [ 5.4081632

In [97]:
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    10: 10 elems, type `int32`, 40 bytes
arr2       ndarray    10: 10 elems, type `int32`, 40 bytes
arr3       ndarray    3x4: 12 elems, type `float64`, 96 bytes
arr4       ndarray    3: 3 elems, type `object`, 24 bytes
arr5       ndarray    3: 3 elems, type `object`, 24 bytes
arr6       ndarray    4x3: 12 elems, type `float64`, 96 bytes
arr7       ndarray    7: 7 elems, type `int32`, 28 bytes
arr8       ndarray    3: 3 elems, type `float64`, 24 bytes
arr9       ndarray    50x3: 150 elems, type `float64`, 1200 bytes
arr_2d     ndarray    3x4: 12 elems, type `int32`, 48 bytes
dir        dict       n=1
i          int        9
j          int        20
list1      list       n=10
list2      list       n=10
list3      list       n=10
list4      list       n=3
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sum        ndarray    10: 10 elems, type `int32`, 40 bytes
